[tool.poetry]
name = "kaskade"
version = "1.1.8"
description = "kaskade is a terminal user interface for kafka"
authors = ["Saúl Piña <sauljabin@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/sauljabin/kaskade"
repository = "https://github.com/sauljabin/kaskade"
documentation = "https://github.com/sauljabin/kaskade"
keywords = ["kafka", "kaskade"]
classifiers = [
    "Environment :: Console",
    "Operating System :: MacOS",
    "Operating System :: Unix"
]
include = [
    "LICENSE",
]
packages = [
    { include = "kaskade" },
]

[tool.poetry.dependencies]
python = ">=3.10 <3.13"
click = "^8.1"
rich = "^13.7"
pyfiglet = "^1.0"
textual =  "^0.70"
confluent-kafka = {extras = ["avro", "json", "protobuf"], version = "^2.4"}

[tool.poetry.dev-dependencies]
black = "*"
faker = "*"
coverage = {extras = ["toml"], version = "*"}
toml = "*"
pre-commit = "*"
ruff = "*"
mypy = "*"
types-attrs = "*"
changeloggh = "*"
textual-dev = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100

[tool.coverage.run]
source = ["kaskade"]
branch = true
omit = [
    "*tests/*",
    "*scripts/*",
    "*__init__.py",
    "*kaskade/app.py",
    "*kaskade/tui.py",
    "*kaskade/renderables/*",
    "*kaskade/widgets/*",
    "*kaskade/__main__.py"
]

[tool.coverage.report]
exclude_lines = ['if __name__ == "__main__":', "@abstractmethod"]

[tool.poetry.scripts]
kaskade = "kaskade.app:main"
kskd = "kaskade.app:main"
