[tool.poetry]
name = "kaskade"
version = "1.1.8"
description = "kaskade is a terminal user interface for kafka"
authors = ["Saúl Piña <sauljabin@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/sauljabin/kaskade"
repository = "https://github.com/sauljabin/kaskade"
documentation = "https://github.com/sauljabin/kaskade"
keywords = ["kafka", "kaskade"]
classifiers = [
    "Environment :: Console",
    "Operating System :: MacOS",
    "Operating System :: Unix"
]
include = [
    "LICENSE",
]
packages = [
    { include = "kaskade" },
]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8"
rich = "^13"
pyfiglet = "^0"
textual =  "^0"
confluent-kafka = {extras = ["avro", "json", "protobuf"], version = "^2"}
PyYAML = "^5"
typing-extensions = "^4"
requests = "^2"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
bandit = "*"
unittest = "*"
Faker = "*"
coverage = {extras = ["toml"], version = "*"}
autoflake = "*"
toml = "^0"
pre-commit = "^2"
flake8 = "*"
mypy = "^0"
types-PyYAML = "^5"
types-attrs = "^19"
types-toml = "^0"
types-setuptools = "^67"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["kaskade"]
branch = true
omit = [
    "*tests/*",
    "*scripts/*",
    "*__init__.py",
    "*kaskade/app.py",
    "*kaskade/tui.py",
    "*kaskade/renderables/*",
    "*kaskade/widgets/*",
    "*kaskade/__main__.py"
]

[tool.coverage.report]
exclude_lines = ['if __name__ == "__main__":', "@abstractmethod"]

[tool.poetry.scripts]
kaskade = "kaskade.app:main"
kskd = "kaskade.app:main"
